// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: lib/api/goback.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Balance       float32                `protobuf:"fixed32,5,opt,name=Balance,proto3" json:"Balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAccountRequest) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRequest) Reset() {
	*x = AccountRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRequest) ProtoMessage() {}

func (x *AccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRequest.ProtoReflect.Descriptor instead.
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{2}
}

func (x *AccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Balance       float32                `protobuf:"fixed32,5,opt,name=Balance,proto3" json:"Balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{3}
}

func (x *AccountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccountResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AccountResponse) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type QuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         string                 `protobuf:"bytes,1,opt,name=Stock,proto3" json:"Stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{4}
}

func (x *QuoteRequest) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

type QuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         string                 `protobuf:"bytes,1,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{5}
}

func (x *QuoteResponse) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *QuoteResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type BuyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{6}
}

type BuyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyResponse) Reset() {
	*x = BuyResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyResponse) ProtoMessage() {}

func (x *BuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyResponse.ProtoReflect.Descriptor instead.
func (*BuyResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{7}
}

type SellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellRequest) Reset() {
	*x = SellRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellRequest) ProtoMessage() {}

func (x *SellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellRequest.ProtoReflect.Descriptor instead.
func (*SellRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{8}
}

type SellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellResponse) Reset() {
	*x = SellResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellResponse) ProtoMessage() {}

func (x *SellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellResponse.ProtoReflect.Descriptor instead.
func (*SellResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{9}
}

type AutoBuyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoBuyRequest) Reset() {
	*x = AutoBuyRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoBuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoBuyRequest) ProtoMessage() {}

func (x *AutoBuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoBuyRequest.ProtoReflect.Descriptor instead.
func (*AutoBuyRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{10}
}

type AutoBuyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoBuyResponse) Reset() {
	*x = AutoBuyResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoBuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoBuyResponse) ProtoMessage() {}

func (x *AutoBuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoBuyResponse.ProtoReflect.Descriptor instead.
func (*AutoBuyResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{11}
}

type AutoSellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoSellRequest) Reset() {
	*x = AutoSellRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoSellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoSellRequest) ProtoMessage() {}

func (x *AutoSellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoSellRequest.ProtoReflect.Descriptor instead.
func (*AutoSellRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{12}
}

type AutoSellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoSellResponse) Reset() {
	*x = AutoSellResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoSellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoSellResponse) ProtoMessage() {}

func (x *AutoSellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoSellResponse.ProtoReflect.Descriptor instead.
func (*AutoSellResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{13}
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{14}
}

func (x *TransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{15}
}

func (x *TransactionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TransactionResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type CancelTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTxRequest) Reset() {
	*x = CancelTxRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTxRequest) ProtoMessage() {}

func (x *CancelTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTxRequest.ProtoReflect.Descriptor instead.
func (*CancelTxRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{16}
}

type CancelTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTxResponse) Reset() {
	*x = CancelTxResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTxResponse) ProtoMessage() {}

func (x *CancelTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTxResponse.ProtoReflect.Descriptor instead.
func (*CancelTxResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{17}
}

type CommitTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTxRequest) Reset() {
	*x = CommitTxRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxRequest) ProtoMessage() {}

func (x *CommitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxRequest.ProtoReflect.Descriptor instead.
func (*CommitTxRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{18}
}

type CommitTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTxResponse) Reset() {
	*x = CommitTxResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxResponse) ProtoMessage() {}

func (x *CommitTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxResponse.ProtoReflect.Descriptor instead.
func (*CommitTxResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{19}
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=TxId,proto3" json:"TxId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Stock         string                 `protobuf:"bytes,4,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Shares        float32                `protobuf:"fixed32,5,opt,name=Shares,proto3" json:"Shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_lib_api_goback_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{20}
}

func (x *Transaction) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Transaction) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *Transaction) GetShares() float32 {
	if x != nil {
		return x.Shares
	}
	return 0
}

var File_lib_api_goback_proto protoreflect.FileDescriptor

const file_lib_api_goback_proto_rawDesc = "" +
	"\n" +
	"\x14lib/api/goback.proto\x12\x03api\"\x96\x01\n" +
	"\x14CreateAccountRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\x12\x18\n" +
	"\aBalance\x18\x05 \x01(\x02R\aBalance\"/\n" +
	"\x15CreateAccountResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\"(\n" +
	"\x0eAccountRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\"\x91\x01\n" +
	"\x0fAccountResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\x12\x18\n" +
	"\aBalance\x18\x05 \x01(\x02R\aBalance\"$\n" +
	"\fQuoteRequest\x12\x14\n" +
	"\x05Stock\x18\x01 \x01(\tR\x05Stock\";\n" +
	"\rQuoteResponse\x12\x14\n" +
	"\x05Stock\x18\x01 \x01(\tR\x05Stock\x12\x14\n" +
	"\x05Price\x18\x02 \x01(\tR\x05Price\"\f\n" +
	"\n" +
	"BuyRequest\"\r\n" +
	"\vBuyResponse\"\r\n" +
	"\vSellRequest\"\x0e\n" +
	"\fSellResponse\"\x10\n" +
	"\x0eAutoBuyRequest\"\x11\n" +
	"\x0fAutoBuyResponse\"\x11\n" +
	"\x0fAutoSellRequest\"\x12\n" +
	"\x10AutoSellResponse\",\n" +
	"\x12TransactionRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\"c\n" +
	"\x13TransactionResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x124\n" +
	"\fTransactions\x18\x02 \x03(\v2\x10.api.TransactionR\fTransactions\"\x11\n" +
	"\x0fCancelTxRequest\"\x12\n" +
	"\x10CancelTxResponse\"\x11\n" +
	"\x0fCommitTxRequest\"\x12\n" +
	"\x10CommitTxResponse\"\x85\x01\n" +
	"\vTransaction\x12\x12\n" +
	"\x04TxId\x18\x01 \x01(\tR\x04TxId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\x12\x1c\n" +
	"\tTimestamp\x18\x03 \x01(\tR\tTimestamp\x12\x14\n" +
	"\x05Stock\x18\x04 \x01(\tR\x05Stock\x12\x16\n" +
	"\x06Shares\x18\x05 \x01(\x02R\x06Shares2\xf6\x04\n" +
	"\x06GoBack\x12H\n" +
	"\rCreateAccount\x12\x19.api.CreateAccountRequest\x1a\x1a.api.CreateAccountResponse\"\x00\x129\n" +
	"\n" +
	"GetAccount\x12\x13.api.AccountRequest\x1a\x14.api.AccountResponse\"\x00\x123\n" +
	"\bGetQuote\x12\x11.api.QuoteRequest\x1a\x12.api.QuoteResponse\"\x00\x120\n" +
	"\tBuyShares\x12\x0f.api.BuyRequest\x1a\x10.api.BuyResponse\"\x00\x123\n" +
	"\n" +
	"SellShares\x12\x10.api.SellRequest\x1a\x11.api.SellResponse\"\x00\x12;\n" +
	"\fAutomatedBuy\x12\x13.api.AutoBuyRequest\x1a\x14.api.AutoBuyResponse\"\x00\x12>\n" +
	"\rAutomatedSell\x12\x14.api.AutoSellRequest\x1a\x15.api.AutoSellResponse\"\x00\x12F\n" +
	"\x0fGetTransactions\x12\x17.api.TransactionRequest\x1a\x18.api.TransactionResponse\"\x00\x12B\n" +
	"\x11CancelTransaction\x12\x14.api.CancelTxRequest\x1a\x15.api.CancelTxResponse\"\x00\x12B\n" +
	"\x11CommitTransaction\x12\x14.api.CommitTxRequest\x1a\x15.api.CommitTxResponse\"\x00B\aZ\x05./apib\x06proto3"

var (
	file_lib_api_goback_proto_rawDescOnce sync.Once
	file_lib_api_goback_proto_rawDescData []byte
)

func file_lib_api_goback_proto_rawDescGZIP() []byte {
	file_lib_api_goback_proto_rawDescOnce.Do(func() {
		file_lib_api_goback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_api_goback_proto_rawDesc), len(file_lib_api_goback_proto_rawDesc)))
	})
	return file_lib_api_goback_proto_rawDescData
}

var file_lib_api_goback_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_lib_api_goback_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),  // 0: api.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 1: api.CreateAccountResponse
	(*AccountRequest)(nil),        // 2: api.AccountRequest
	(*AccountResponse)(nil),       // 3: api.AccountResponse
	(*QuoteRequest)(nil),          // 4: api.QuoteRequest
	(*QuoteResponse)(nil),         // 5: api.QuoteResponse
	(*BuyRequest)(nil),            // 6: api.BuyRequest
	(*BuyResponse)(nil),           // 7: api.BuyResponse
	(*SellRequest)(nil),           // 8: api.SellRequest
	(*SellResponse)(nil),          // 9: api.SellResponse
	(*AutoBuyRequest)(nil),        // 10: api.AutoBuyRequest
	(*AutoBuyResponse)(nil),       // 11: api.AutoBuyResponse
	(*AutoSellRequest)(nil),       // 12: api.AutoSellRequest
	(*AutoSellResponse)(nil),      // 13: api.AutoSellResponse
	(*TransactionRequest)(nil),    // 14: api.TransactionRequest
	(*TransactionResponse)(nil),   // 15: api.TransactionResponse
	(*CancelTxRequest)(nil),       // 16: api.CancelTxRequest
	(*CancelTxResponse)(nil),      // 17: api.CancelTxResponse
	(*CommitTxRequest)(nil),       // 18: api.CommitTxRequest
	(*CommitTxResponse)(nil),      // 19: api.CommitTxResponse
	(*Transaction)(nil),           // 20: api.Transaction
}
var file_lib_api_goback_proto_depIdxs = []int32{
	20, // 0: api.TransactionResponse.Transactions:type_name -> api.Transaction
	0,  // 1: api.GoBack.CreateAccount:input_type -> api.CreateAccountRequest
	2,  // 2: api.GoBack.GetAccount:input_type -> api.AccountRequest
	4,  // 3: api.GoBack.GetQuote:input_type -> api.QuoteRequest
	6,  // 4: api.GoBack.BuyShares:input_type -> api.BuyRequest
	8,  // 5: api.GoBack.SellShares:input_type -> api.SellRequest
	10, // 6: api.GoBack.AutomatedBuy:input_type -> api.AutoBuyRequest
	12, // 7: api.GoBack.AutomatedSell:input_type -> api.AutoSellRequest
	14, // 8: api.GoBack.GetTransactions:input_type -> api.TransactionRequest
	16, // 9: api.GoBack.CancelTransaction:input_type -> api.CancelTxRequest
	18, // 10: api.GoBack.CommitTransaction:input_type -> api.CommitTxRequest
	1,  // 11: api.GoBack.CreateAccount:output_type -> api.CreateAccountResponse
	3,  // 12: api.GoBack.GetAccount:output_type -> api.AccountResponse
	5,  // 13: api.GoBack.GetQuote:output_type -> api.QuoteResponse
	7,  // 14: api.GoBack.BuyShares:output_type -> api.BuyResponse
	9,  // 15: api.GoBack.SellShares:output_type -> api.SellResponse
	11, // 16: api.GoBack.AutomatedBuy:output_type -> api.AutoBuyResponse
	13, // 17: api.GoBack.AutomatedSell:output_type -> api.AutoSellResponse
	15, // 18: api.GoBack.GetTransactions:output_type -> api.TransactionResponse
	17, // 19: api.GoBack.CancelTransaction:output_type -> api.CancelTxResponse
	19, // 20: api.GoBack.CommitTransaction:output_type -> api.CommitTxResponse
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_lib_api_goback_proto_init() }
func file_lib_api_goback_proto_init() {
	if File_lib_api_goback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_api_goback_proto_rawDesc), len(file_lib_api_goback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_api_goback_proto_goTypes,
		DependencyIndexes: file_lib_api_goback_proto_depIdxs,
		MessageInfos:      file_lib_api_goback_proto_msgTypes,
	}.Build()
	File_lib_api_goback_proto = out.File
	file_lib_api_goback_proto_goTypes = nil
	file_lib_api_goback_proto_depIdxs = nil
}
