// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: lib/api/goback.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Balance       float32                `protobuf:"fixed32,5,opt,name=Balance,proto3" json:"Balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAccountRequest) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRequest) Reset() {
	*x = AccountRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRequest) ProtoMessage() {}

func (x *AccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRequest.ProtoReflect.Descriptor instead.
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{2}
}

func (x *AccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Balance       float32                `protobuf:"fixed32,5,opt,name=Balance,proto3" json:"Balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{3}
}

func (x *AccountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccountResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AccountResponse) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type QuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         string                 `protobuf:"bytes,1,opt,name=Stock,proto3" json:"Stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{4}
}

func (x *QuoteRequest) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

type QuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         string                 `protobuf:"bytes,1,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{5}
}

func (x *QuoteResponse) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *QuoteResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type TxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Stock         string                 `protobuf:"bytes,3,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Shares        float32                `protobuf:"fixed32,4,opt,name=Shares,proto3" json:"Shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxRequest) Reset() {
	*x = TxRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRequest) ProtoMessage() {}

func (x *TxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRequest.ProtoReflect.Descriptor instead.
func (*TxRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{6}
}

func (x *TxRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TxRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TxRequest) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *TxRequest) GetShares() float32 {
	if x != nil {
		return x.Shares
	}
	return 0
}

type TxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Stock         string                 `protobuf:"bytes,4,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Shares        float32                `protobuf:"fixed32,5,opt,name=Shares,proto3" json:"Shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxResponse) Reset() {
	*x = TxResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxResponse) ProtoMessage() {}

func (x *TxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxResponse.ProtoReflect.Descriptor instead.
func (*TxResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{7}
}

func (x *TxResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *TxResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TxResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TxResponse) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *TxResponse) GetShares() float32 {
	if x != nil {
		return x.Shares
	}
	return 0
}

type TransactionLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionLogRequest) Reset() {
	*x = TransactionLogRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLogRequest) ProtoMessage() {}

func (x *TransactionLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLogRequest.ProtoReflect.Descriptor instead.
func (*TransactionLogRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionLogRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TransactionLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionLogResponse) Reset() {
	*x = TransactionLogResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLogResponse) ProtoMessage() {}

func (x *TransactionLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLogResponse.ProtoReflect.Descriptor instead.
func (*TransactionLogResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionLogResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TransactionLogResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type CancelTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTxRequest) Reset() {
	*x = CancelTxRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTxRequest) ProtoMessage() {}

func (x *CancelTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTxRequest.ProtoReflect.Descriptor instead.
func (*CancelTxRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{10}
}

type CancelTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTxResponse) Reset() {
	*x = CancelTxResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTxResponse) ProtoMessage() {}

func (x *CancelTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTxResponse.ProtoReflect.Descriptor instead.
func (*CancelTxResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{11}
}

type CommitTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTxRequest) Reset() {
	*x = CommitTxRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxRequest) ProtoMessage() {}

func (x *CommitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxRequest.ProtoReflect.Descriptor instead.
func (*CommitTxRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{12}
}

type CommitTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTxResponse) Reset() {
	*x = CommitTxResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxResponse) ProtoMessage() {}

func (x *CommitTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxResponse.ProtoReflect.Descriptor instead.
func (*CommitTxResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{13}
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=TxId,proto3" json:"TxId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Stock         string                 `protobuf:"bytes,5,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Shares        float32                `protobuf:"fixed32,6,opt,name=Shares,proto3" json:"Shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_lib_api_goback_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{14}
}

func (x *Transaction) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Transaction) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

func (x *Transaction) GetShares() float32 {
	if x != nil {
		return x.Shares
	}
	return 0
}

var File_lib_api_goback_proto protoreflect.FileDescriptor

const file_lib_api_goback_proto_rawDesc = "" +
	"\n" +
	"\x14lib/api/goback.proto\x12\x03api\"\x96\x01\n" +
	"\x14CreateAccountRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\x12\x18\n" +
	"\aBalance\x18\x05 \x01(\x02R\aBalance\"/\n" +
	"\x15CreateAccountResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\"(\n" +
	"\x0eAccountRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\"\x91\x01\n" +
	"\x0fAccountResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\x12\x18\n" +
	"\aBalance\x18\x05 \x01(\x02R\aBalance\"$\n" +
	"\fQuoteRequest\x12\x14\n" +
	"\x05Stock\x18\x01 \x01(\tR\x05Stock\";\n" +
	"\rQuoteResponse\x12\x14\n" +
	"\x05Stock\x18\x01 \x01(\tR\x05Stock\x12\x14\n" +
	"\x05Price\x18\x02 \x01(\tR\x05Price\"e\n" +
	"\tTxRequest\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\x12\x14\n" +
	"\x05Stock\x18\x03 \x01(\tR\x05Stock\x12\x16\n" +
	"\x06Shares\x18\x04 \x01(\x02R\x06Shares\"\x84\x01\n" +
	"\n" +
	"TxResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\bR\x06Status\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\x12\x1c\n" +
	"\tTimestamp\x18\x03 \x01(\tR\tTimestamp\x12\x14\n" +
	"\x05Stock\x18\x04 \x01(\tR\x05Stock\x12\x16\n" +
	"\x06Shares\x18\x05 \x01(\x02R\x06Shares\"/\n" +
	"\x15TransactionLogRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\"f\n" +
	"\x16TransactionLogResponse\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\tR\x06UserId\x124\n" +
	"\fTransactions\x18\x02 \x03(\v2\x10.api.TransactionR\fTransactions\"\x11\n" +
	"\x0fCancelTxRequest\"\x12\n" +
	"\x10CancelTxResponse\"\x11\n" +
	"\x0fCommitTxRequest\"\x12\n" +
	"\x10CommitTxResponse\"\x99\x01\n" +
	"\vTransaction\x12\x12\n" +
	"\x04TxId\x18\x01 \x01(\tR\x04TxId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\tR\x04Type\x12\x1c\n" +
	"\tTimestamp\x18\x04 \x01(\tR\tTimestamp\x12\x14\n" +
	"\x05Stock\x18\x05 \x01(\tR\x05Stock\x12\x16\n" +
	"\x06Shares\x18\x06 \x01(\x02R\x06Shares2\x9b\x03\n" +
	"\x06GoBack\x12H\n" +
	"\rCreateAccount\x12\x19.api.CreateAccountRequest\x1a\x1a.api.CreateAccountResponse\"\x00\x129\n" +
	"\n" +
	"GetAccount\x12\x13.api.AccountRequest\x1a\x14.api.AccountResponse\"\x00\x123\n" +
	"\bGetQuote\x12\x11.api.QuoteRequest\x1a\x12.api.QuoteResponse\"\x00\x12O\n" +
	"\x12GetTransactionLogs\x12\x1a.api.TransactionLogRequest\x1a\x1b.api.TransactionLogResponse\"\x00\x12B\n" +
	"\x11CancelTransaction\x12\x14.api.CancelTxRequest\x1a\x15.api.CancelTxResponse\"\x00\x12B\n" +
	"\x11CommitTransaction\x12\x14.api.CommitTxRequest\x1a\x15.api.CommitTxResponse\"\x00B\aZ\x05./apib\x06proto3"

var (
	file_lib_api_goback_proto_rawDescOnce sync.Once
	file_lib_api_goback_proto_rawDescData []byte
)

func file_lib_api_goback_proto_rawDescGZIP() []byte {
	file_lib_api_goback_proto_rawDescOnce.Do(func() {
		file_lib_api_goback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_api_goback_proto_rawDesc), len(file_lib_api_goback_proto_rawDesc)))
	})
	return file_lib_api_goback_proto_rawDescData
}

var file_lib_api_goback_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_lib_api_goback_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),   // 0: api.CreateAccountRequest
	(*CreateAccountResponse)(nil),  // 1: api.CreateAccountResponse
	(*AccountRequest)(nil),         // 2: api.AccountRequest
	(*AccountResponse)(nil),        // 3: api.AccountResponse
	(*QuoteRequest)(nil),           // 4: api.QuoteRequest
	(*QuoteResponse)(nil),          // 5: api.QuoteResponse
	(*TxRequest)(nil),              // 6: api.TxRequest
	(*TxResponse)(nil),             // 7: api.TxResponse
	(*TransactionLogRequest)(nil),  // 8: api.TransactionLogRequest
	(*TransactionLogResponse)(nil), // 9: api.TransactionLogResponse
	(*CancelTxRequest)(nil),        // 10: api.CancelTxRequest
	(*CancelTxResponse)(nil),       // 11: api.CancelTxResponse
	(*CommitTxRequest)(nil),        // 12: api.CommitTxRequest
	(*CommitTxResponse)(nil),       // 13: api.CommitTxResponse
	(*Transaction)(nil),            // 14: api.Transaction
}
var file_lib_api_goback_proto_depIdxs = []int32{
	14, // 0: api.TransactionLogResponse.Transactions:type_name -> api.Transaction
	0,  // 1: api.GoBack.CreateAccount:input_type -> api.CreateAccountRequest
	2,  // 2: api.GoBack.GetAccount:input_type -> api.AccountRequest
	4,  // 3: api.GoBack.GetQuote:input_type -> api.QuoteRequest
	8,  // 4: api.GoBack.GetTransactionLogs:input_type -> api.TransactionLogRequest
	10, // 5: api.GoBack.CancelTransaction:input_type -> api.CancelTxRequest
	12, // 6: api.GoBack.CommitTransaction:input_type -> api.CommitTxRequest
	1,  // 7: api.GoBack.CreateAccount:output_type -> api.CreateAccountResponse
	3,  // 8: api.GoBack.GetAccount:output_type -> api.AccountResponse
	5,  // 9: api.GoBack.GetQuote:output_type -> api.QuoteResponse
	9,  // 10: api.GoBack.GetTransactionLogs:output_type -> api.TransactionLogResponse
	11, // 11: api.GoBack.CancelTransaction:output_type -> api.CancelTxResponse
	13, // 12: api.GoBack.CommitTransaction:output_type -> api.CommitTxResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_lib_api_goback_proto_init() }
func file_lib_api_goback_proto_init() {
	if File_lib_api_goback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_api_goback_proto_rawDesc), len(file_lib_api_goback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_api_goback_proto_goTypes,
		DependencyIndexes: file_lib_api_goback_proto_depIdxs,
		MessageInfos:      file_lib_api_goback_proto_msgTypes,
	}.Build()
	File_lib_api_goback_proto = out.File
	file_lib_api_goback_proto_goTypes = nil
	file_lib_api_goback_proto_depIdxs = nil
}
