syntax = "proto3";
option go_package = "./api";
package api;

service GoBack {
    rpc CreateAccount(CreateAccountRequest) returns (CreateAccountResponse) {};
    rpc GetAccount(AccountRequest) returns (AccountResponse) {};
    rpc AddBalance(BalanceRequest) returns (BalanceResponse) {};
    rpc GetPortfolio(PortfolioRequest) returns (PortfolioResponse) {};
    rpc GetQuote(QuoteRequest) returns (QuoteResponse) {};
    rpc GetTransactionLogs(TransactionLogRequest) returns (TransactionLogResponse) {};
    rpc CancelTransaction(CancelTxRequest) returns (CancelTxResponse) {};
    rpc CommitTransaction(CommitTxRequest) returns (CommitTxResponse) {};
}

message CreateAccountRequest {
    string UserId = 1;
    string Username = 2;
    string Email = 3;
    string Password = 4;
    double Balance = 5;
}
message CreateAccountResponse {
    string UserId = 1;
}
message AccountRequest {
    string UserId = 1;
}
message AccountResponse {
    string UserId = 1;
    string Username = 2;
    string Email = 3;
    string Password = 4;
    double Balance = 5;
}
message BalanceRequest {
    string UserId = 1;
    double AddAmount = 2;
}
message BalanceResponse {
    bool   Status = 1;
    double NewBalance = 2;
}
message PortfolioRequest {
    string UserId = 1;
}
message PortfolioLog {
    string UserId = 1;
    string Stock = 2;
    double Shares = 3;
}
message PortfolioResponse {
    string UserId = 1;
    repeated PortfolioLog PortfolioLogs = 2;
}
message QuoteRequest {
    string Stock = 1;
}
message QuoteResponse {
    string Stock = 1;
    string Price = 2;
}
message TxRequest {
    string Type = 1;
    string UserId = 2;
    string Stock = 3;
    double Shares = 4;
    double SharePrice = 5;
}
message TxResponse {
    bool   Status = 1;
    string Type = 2;
    string Timestamp = 3;
    string Stock = 4;
    double Shares = 5;
    double TotalCost = 6;
}
message TransactionLogRequest {
    string UserId = 1;
}
message TransactionLogResponse {
    string UserId = 1;
    repeated TransactionLog TransactionLogs = 2;
}
message CancelTxRequest {}
message CancelTxResponse {}
message CommitTxRequest {}
message CommitTxResponse {}
message TransactionLog {
    string TxId = 1;
    string UserId = 2;
    string Type = 3;
    string Timestamp = 4;
    string Stock = 5;
    double Shares = 6;
    double SharePrice = 7;
}
