syntax = "proto3";
option go_package = "./api";
package api;

service GoBack {
    rpc CreateAccount(CreateAccountRequest) returns (CreateAccountResponse) {};
    rpc GetAccount(AccountRequest) returns (AccountResponse) {};
    rpc GetQuote(QuoteRequest) returns (QuoteResponse) {};
    rpc BuyShares(BuyRequest) returns (BuyResponse) {};
    rpc SellShares(SellRequest) returns (SellResponse) {};
    rpc AutomatedBuy(AutoBuyRequest) returns (AutoBuyResponse) {};
    rpc AutomatedSell(AutoSellRequest) returns (AutoSellResponse) {};
    rpc GetTransactions(TransactionRequest) returns (TransactionResponse) {};
    rpc CancelTransaction(CancelTxRequest) returns (CancelTxResponse) {};
    rpc CommitTransaction(CommitTxRequest) returns (CommitTxResponse) {};
}

message CreateAccountRequest {
    string UserId = 1;
    string Username = 2;
    string Email = 3;
    string Password = 4;
    float  Balance = 5;
}
message CreateAccountResponse {
    string UserId = 1;
}
message AccountRequest {
    string UserId = 1;
}
message AccountResponse {
    string UserId = 1;
    string Username = 2;
    string Email = 3;
    string Password = 4;
    float  Balance = 5;
}
message QuoteRequest {
    string Stock = 1;
}
message QuoteResponse {
    string Stock = 1;
    string Price = 2;
}
message BuyRequest {}
message BuyResponse {}
message SellRequest {}
message SellResponse {}
message AutoBuyRequest {}
message AutoBuyResponse {}
message AutoSellRequest {}
message AutoSellResponse {}
message TransactionRequest {
    string UserId = 1;
}
message TransactionResponse {
    string UserId = 1;
    repeated Transaction Transactions = 2;
}
message CancelTxRequest {}
message CancelTxResponse {}
message CommitTxRequest {}
message CommitTxResponse {}
message Transaction {
    string TxId = 1;
    string UserId = 2;
    string Timestamp = 3;
    string Stock = 4;
    float  Shares = 5;
}
