// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: lib/api/goback.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegRequest) Reset() {
	*x = RegRequest{}
	mi := &file_lib_api_goback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegRequest) ProtoMessage() {}

func (x *RegRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegRequest.ProtoReflect.Descriptor instead.
func (*RegRequest) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{0}
}

func (x *RegRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type RegResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registered    bool                   `protobuf:"varint,1,opt,name=Registered,proto3" json:"Registered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegResponse) Reset() {
	*x = RegResponse{}
	mi := &file_lib_api_goback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegResponse) ProtoMessage() {}

func (x *RegResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_api_goback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegResponse.ProtoReflect.Descriptor instead.
func (*RegResponse) Descriptor() ([]byte, []int) {
	return file_lib_api_goback_proto_rawDescGZIP(), []int{1}
}

func (x *RegResponse) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

var File_lib_api_goback_proto protoreflect.FileDescriptor

const file_lib_api_goback_proto_rawDesc = "" +
	"\n" +
	"\x14lib/api/goback.proto\x12\x03api\"(\n" +
	"\n" +
	"RegRequest\x12\x1a\n" +
	"\bDeviceId\x18\x01 \x01(\tR\bDeviceId\"-\n" +
	"\vRegResponse\x12\x1e\n" +
	"\n" +
	"Registered\x18\x01 \x01(\bR\n" +
	"Registered2:\n" +
	"\aGateway\x12/\n" +
	"\bRegister\x12\x0f.api.RegRequest\x1a\x10.api.RegResponse\"\x00B\aZ\x05./apib\x06proto3"

var (
	file_lib_api_goback_proto_rawDescOnce sync.Once
	file_lib_api_goback_proto_rawDescData []byte
)

func file_lib_api_goback_proto_rawDescGZIP() []byte {
	file_lib_api_goback_proto_rawDescOnce.Do(func() {
		file_lib_api_goback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_api_goback_proto_rawDesc), len(file_lib_api_goback_proto_rawDesc)))
	})
	return file_lib_api_goback_proto_rawDescData
}

var file_lib_api_goback_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lib_api_goback_proto_goTypes = []any{
	(*RegRequest)(nil),  // 0: api.RegRequest
	(*RegResponse)(nil), // 1: api.RegResponse
}
var file_lib_api_goback_proto_depIdxs = []int32{
	0, // 0: api.Gateway.Register:input_type -> api.RegRequest
	1, // 1: api.Gateway.Register:output_type -> api.RegResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_api_goback_proto_init() }
func file_lib_api_goback_proto_init() {
	if File_lib_api_goback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_api_goback_proto_rawDesc), len(file_lib_api_goback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_api_goback_proto_goTypes,
		DependencyIndexes: file_lib_api_goback_proto_depIdxs,
		MessageInfos:      file_lib_api_goback_proto_msgTypes,
	}.Build()
	File_lib_api_goback_proto = out.File
	file_lib_api_goback_proto_goTypes = nil
	file_lib_api_goback_proto_depIdxs = nil
}
