services:
  gateway:
    build:
      dockerfile: ./services/gateway/Containerfile
    depends_on:
        - txserver
    ports:
      - 8000:8000
    restart: on-failure
    networks:
      - exchange

  quote:
    build:
      dockerfile: ./services/quote/Containerfile
    ports:
      - 4444:4444
    restart: on-failure
    networks:
      - exchange

  txserver:
    build:
      dockerfile: ./services/txserver/Containerfile
    depends_on:
      - cockroach
      - redis
      - rmq
      - quote
    environment:
      - DB_URL=postgresql://root@cockroach:26257/defaultdb?sslmode=disable
    ports:
      - 50051:50051
    restart: on-failure
    networks:
      - exchange

  cockroach:
    image: cockroachdb/cockroach:latest
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node --insecure
    environment:
      - COCKROACH_DATABASE=${COCKROACH_DATABASE:-defaultdb}
    networks:
      - exchange

  rmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15692:15692
    networks:
      - exchange

  redis:
    image: redis:latest
    restart: on-failure
    ports:
      - 6379:6379
    post_start:
      - command: sh -c "redis-cli CONFIG SET maxmemory 50mb && redis-cli CONFIG SET maxmemory-policy volatile-ttl"
    networks:
      - exchange

networks:
  exchange:
    driver: bridge
