FROM docker.io/golang:1.27-trixie AS builder
WORKDIR /goback
RUN apt update && apt -y dist-upgrade
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /bin/gateway ./services/gateway

FROM scratch AS runtime
COPY --from=builder /bin/gateway /bin/gateway
EXPOSE 8000
EXPOSE 50051
ENTRYPOINT ["/bin/gateway"]
